name: Deploy to Production

on:
  push:
    branches: [ production ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🌈 Deploy with ssh...
        uses: sebastianjnuwu/ssh-action-deploy@v3
        with:
          IP: 35.154.59.41
          USER: ubuntu
          KEY: ${{ secrets.ORGANIZATION_SSH_KEY }}
          FOLDER: "/home/bhavicreations/domains/gittest.bhavicreations.com/public_html"
          RUN: "git pull -v origin production"