name: Deploy to Production

on:
  push:
    branches: [ production ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🌈 Deploy with ssh...
        uses: sebastianjnuwu/ssh-action-deploy@v3
        with:
          host: 35.154.59.41
          username: ubuntu
          key: ${{ secrets.ORGANIZATION_SSH_KEY }}
          command: 'cd /home/bhavicreations/domains/gittest.bhavicreations.com/public_html && git pull origin production'