name: Deploy to Production

on:
  push:
    branches: [ production ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - id: ssh
        uses: invi5H/ssh-action@v1
        with:
          SSH_HOST: 35.154.59.41
          SSH_USER: ubuntu
          SSH_KEY: ${{ secrets.ORGANIZATION_SSH_KEY }}
      - name: Deploy code
        run: |
          ssh -T ubuntu@35.154.59.41 '
            cd /home/bhavicreations/domains/gittest.bhavicreations.com/public_html  # Replace with the path to your website directory
            git pull origin production
          '
